---
name: Default
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

jobs:
  main:
    # TODO: ubuntu 24.04 because we target GNOME >= 46, once 24.04 becomes
    # "latest" then we can switch back to ubuntu-latest
    runs-on: ubuntu-24.04

    steps:
      - run: sudo apt-get install -y gnome-shell
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: extension
          path: "*.zip"
